version: '3.8'

services:
  # PostgreSQL Database (Development)
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rest_api_builder
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Development Server
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/rest_api_builder?schema=public
      PORT: 3001
      CORS_ORIGIN: http://localhost:3000
      API_PREFIX: /api
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - node_modules_dev:/app/node_modules
    command: >
      sh -c "npx prisma migrate dev --name init &&
             npx prisma generate &&
             yarn dev"

volumes:
  postgres_data_dev:
  node_modules_dev: